version: '3.7'
services:
  chat_bot:
    container_name: chat_bot
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    environment:
      - "TZ=America/Fortaleza"